# Generated by Django 4.1 on 2023-04-08 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Мұражай атауы')),
                ('description', models.TextField(verbose_name='Сипаттамасы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='museum_images/', verbose_name='Сурет')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған күн')),
            ],
            options={
                'verbose_name': 'Музей',
                'verbose_name_plural': 'Музейлер',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тегі')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон номері')),
                ('admin_status', models.BooleanField(default=False, verbose_name='Админ статусы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жүйе қолданушы',
                'verbose_name_plural': 'Жүйе қолданушы',
            },
        ),
        migrations.CreateModel(
            name='MuseumImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='museum_shots/', verbose_name='Сурет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.museum')),
            ],
            options={
                'verbose_name': 'Сурет',
                'verbose_name_plural': 'Суреттер',
            },
        ),
    ]
