# Generated by Django 4.1 on 2023-04-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_museum_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Экспонат аты')),
                ('image', models.ImageField(upload_to='museum_shots/', verbose_name='Сурет')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.museum')),
            ],
            options={
                'verbose_name': 'Сурет',
                'verbose_name_plural': 'Суреттер',
            },
        ),
    ]
