# Generated by Django 4.1 on 2023-04-15 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_museumimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='museumimages',
            options={'verbose_name': 'Көрме залы', 'verbose_name_plural': 'Көрме залдары'},
        ),
        migrations.AddField(
            model_name='users',
            name='museum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.museum', verbose_name='Жұмыс орны'),
        ),
        migrations.AddField(
            model_name='users',
            name='position',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Лауазымы'),
        ),
        migrations.AlterField(
            model_name='museumimages',
            name='museum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.museum', verbose_name='Мұражай'),
        ),
        migrations.AlterField(
            model_name='museumimages',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Зал аты'),
        ),
        migrations.CreateModel(
            name='Exhibits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Экспонат аты')),
                ('image', models.ImageField(upload_to='exhibits_shots/', verbose_name='Сурет')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сипаттамасы')),
                ('period', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тарихи кезең')),
                ('belongs', models.CharField(blank=True, max_length=250, null=True, verbose_name='Кімге тиесілі')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.museum', verbose_name='Мұражай')),
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаттар',
            },
        ),
    ]
