# Generated by Django 4.1 on 2023-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_museumimages_options_users_museum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibits',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Слаг'),
        ),
    ]
